### ISSUE TITLE
QSPI addressing doesn't work in v0.35

### ISSUE THREAD

**Issue by daniestevez** [MicroPhase/antsdr-fw-patch#13]
I have found this issue while trying to program the QSPI with the Maia SDR firmware image from Linux running the v0.35 image.

The problem is that the >16MiB addressing of the 32MiB QSPI flash is not handled correctly. While reading and writing `/dev/mtdblock?` from Linux, accesses to the upper 16MiB wrap around and end up accessing the lower 16MiB. This causes that writing the FIT image to `/dev/mtdblock3` overwrites the bootloader partition (the FIT image is 17 MiB).

Looking in the kernel sources used in v0.35, it seems that when using the Zynq QSPI controller, accesses are done with 3 byte addressing, so the EAR register needs to be set correctly for each access. However, [`spi_nor_write_ear()`](https://github.com/analogdevicesinc/linux/blob/9c04de11ae53e7c48b57e6153b4a0df241e094ad/drivers/mtd/spi-nor/spi-nor.c#L689) doesn't seem to handle correctly the Winbond QSPI used in the AntSDR E200. This device is handled using the generic case, and so `write_enable()` is not called. According to [Section 8.2.7 in the datasheet](https://docs.rs-online.com/29d5/0900766b81703fc1.pdf), write enable needs to be done before modifying the EAR register.

In any case, modern versions of the Pluto firmware (such as v0.38) use a more recent kernel version in which the `spi-nor` code has been refactored. Perhaps this problem doesn't happen in the newer kernel version. Therefore, updating the kernel instead of patching the problem might be a better solution.

I haven't tested any of the potential solutions to this issue.

**Comment by lone-boy** [comment]
Yes, qspi cannot be used when it is larger than 16M. Please rest assured that we are working on building the latest version of plutov0.38, which will solve this problem.

**Comment by daniestevez** [comment]
This problem has been solved in the v0.38 branch. Closing.
