### ISSUE TITLE
Why the IOSTANDARD of gpio_ctl is LVCMOS33?

### ISSUE THREAD

**Issue by ruanzhibin** [MicroPhase/antsdr-fw-patch#14]
The iostandard of gpio_ctl of ad9361 shall follow the VDD_INTERFACE ,which should be 1.8v in your design. 
But in the system.xdc of your design , the iostandard is  as follows:
"+set_property IOSTANDARD LVCMOS33 [get_ports {gpio_ctl[3]}]"

Why? Is it a mistake?

**Comment by lone-boy** [comment]
It actually depends on the physical link, if LVCMOS33 is not allocated here, your project synthesis will not pass.
