### ISSUE TITLE
Second channel can't use

### ISSUE THREAD

**Issue by tclin0122** [MicroPhase/antsdr-fw-patch#15]
I updated my ANTSDR E310 with the 0.34 release. And it can also be configured to 2r2t mode in firmware. However, when I try to enable the second channel with python, I get some error messages as below

'''
raise Exception("TX mapping exceeds available channels")
Exception: TX mapping exceeds available channels
'''

**Comment by lone-boy** [comment]
Maybe the second channel is still not open at this time. You can try to compile a v0.38 version to give it a try, or use the sd 2r2t mode of v0.34. If you need it, I can provide you with a 2r2t image.

**Comment by tclin0122** [comment]
Yes! Since I'm using a Mac, I cannot compile the image recently. It will be very beneficial if you can provide the 2r2t image. Thanks for your help!

**Comment by lone-boy** [comment]
Sorry for a late reply, this is the firmware booted from the sd card, you can try it.
[2r2t sd.zip](https://github.com/MicroPhase/antsdr-fw-patch/files/14427883/2r2t.sd.zip)

**Comment by tclin0122** [comment]
Hi! sorry for the late reply. Yes, it works now! Thank you so much!
