### ISSUE TITLE
 mknod: /home/brendensdr/antsdr-fw-patch/plutosdr-fw/buildroot/output/build/buildroot-fs/cpio/target/dev/console: Operation not permitted

### ISSUE THREAD

**Issue by BrendenWiley** [MicroPhase/antsdr-fw-patch#16]
Hello

I am running into issues building v0.34 firmware for the E200 AntSDR. I am using Ubuntu version 22.04 and Vivado 2019.1. Any help is greatly appreciated.

The error I am experiencing is as follows: mknod: /home/brendensdr/antsdr-fw-patch/plutosdr-fw/buildroot/output/build/buildroot-fs/cpio/target/dev/console: Operation not permitted

Thanks

**Comment by lone-boy** [comment]
This seems to be a permissions issue. In what directory did you build it? Have you tried make clean and then make again?
