### ISSUE TITLE
How install Xilinx Vivado to get SDK?

### ISSUE THREAD

**Issue by nik13513513** [MicroPhase/antsdr-fw-patch#2]
Hello, after installing vivado/vitis i have directory structure like this:
![изображение](https://user-images.githubusercontent.com/24268437/212269296-625c41f5-b439-4610-b8e6-f01317e94ac2.png)

No folder SDK. 
I need install something else?

**Comment by black-pigeon** [comment]
For plutosdr v0.35, you need vivado/sdk 2019.1 to compile the buildroot, and vivado 2021.1 to build the fpga project.
> v0.35
> export CROSS_COMPILE=arm-linux-gnueabihf- 
> export PATH=$PATH:/opt/Xilinx/SDK/2019.1/gnu/aarch32/lin/gcc-arm-linux-gnueabi/bin 
> export VIVADO_SETTINGS=/opt/Xilinx/Vivado/2021.1/settings64.sh
> export PERL_MM_OPT=

**Comment by lone-boy** [comment]
issue has been resolved,close it now.
