### ISSUE TITLE
EEPROM usage

### ISSUE THREAD

**Issue by deskl0** [MicroPhase/antsdr-fw-patch#4]
Greetings! I've received an ANTSDR e200 from our RF lab. Unfortunately, neither my instructor nor the RF lab provides no technical support information, I wonder may the creator of this device could help me out. And I am modifying firmware for our research project, which may require quite a lot of room for calibration data and preferences. I've noticed an EEPROM mounted on the backside(designator U47), I'd like to know what purpose it is, and can I use them for data storage purposes? If it is possible, can all sectors be utilized? It will be easier for data alignment.

**Comment by lone-boy** [comment]
Hello, about technical support, there is a piece of after-sales service that needs to contact us. If it is to store data, I recommend putting it in the sd card.

**Comment by deskl0** [comment]
Thanks for your reply. I intend to use the SD card for raw samples and preliminarily processed results, which would be easier to dump. As for calibration data, they are very dependent on device and freq, thus, it will be better if they could be stored in eeprom so others wouldn't bother with calibration issues. Is this goal achievable?
