### ISSUE TITLE
Can't build sd image

### ISSUE THREAD

**Issue by DarkSov** [MicroPhase/antsdr-fw-patch#6]
The firmware itself builds without any  problems, but I can't build sd image for e310.
Here's output:
```
bash -c "source /opt/Xilinx/Vivado/2021.1/settings64.sh && bootgen -image /home/user/Documents/antsdr/antsdr-fw-patch/plutosdr-fw/build_sdimg/boot.bif -o i /home/user/Documents/antsdr/antsdr-fw-patch/plutosdr-fw/build_sdimg/BOOT.bin"


****** Xilinx Bootgen v2021.1
  **** Build date : Jun 10 2021-20:11:31
    ** Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.


ERROR:BootGen - syntax error
   Line #1, "/home/user/Documents/antsdr/antsdr-fw-patch/plutosdr-fw/build_sdimg/boot.bif".
image : {[bootloader] /home/user/Documents/antsdr/antsdr-fw-patch/plut
^^^^^

[ERROR]  : BIF file parsing failed with code 1
make: *** [Makefile:210: sdimg] Error 1
```

**Comment by lone-boy** [comment]
@DarkSov hello, If you want to build sd image, you can run make sdimg after build.

**Comment by DarkSov** [comment]
That's what I have done

**Comment by lone-boy** [comment]
I just reproduced it again, and it was successfully compiled. I see that your information is the compiled v0.35 version, so it corresponds to vivado 21. I guess it is your environment problem. Can you tell me which version of vivado you use?

**Comment by DarkSov** [comment]
Sorry for late response, I'm using Vivado 2021.1

**Comment by lone-boy** [comment]
Ok, I fix it. You can pull and build again.

**Comment by DarkSov** [comment]
Thanks, everything works now
