### ISSUE TITLE
Device not detected by SoapySDR

### ISSUE THREAD

**Issue by BatchDrake** [MicroPhase/antsdr-fw-patch#7]
Hello,

I am using an ANTSDR E310. I can connect to it via ssh in 192.168.2.1, using the well known root/analog credentials. I've just installed the SoapySDR module for Pluto (https://github.com/pothosware/SoapyPlutoSDR) hoping that, since this is also based on libiio, it should be detected by the PlutoSDR module. Unfortunately, it is not the case. Neither automatically, nor with `SoapySDRUtil --probe="driver=plutosdr,hostname=192.168.2.1"`. `iiod` is running correctly too:

```
  875 root     /usr/sbin/iiod -D -n 3 -F /dev/iio_ffs
```

Additionally, the Ethernet interface does not seem to work, neither with static IP, nor via DHCP. This issue does not occur with the OpenWifi firmware (in fact, I used the Ethernet port regularly).

Cheers,

**Comment by BatchDrake** [comment]
Hi again,

I believe I've found the problem, I am using the older AntSDR E310, not the E310v2. The existing released firmware does not seem to support E310. Could you make a release that works with E310?

Cheers,

**Comment by AlexeyBarsuk** [comment]
You should use ant.zip from releases folder - it is for e310

**Comment by lone-boy** [comment]
@BatchDrake 
Sorry for replying so late. Antsdr E310 firmware is ant. https://github.com/MicroPhase/antsdr-fw-patch/releases/download/v0.34/ant.zip

**Comment by BatchDrake** [comment]
No worries, the experiment worked seamlessly (see [the entry](https://batchdrake.github.io/rdf-ii)), thank you!
