### ISSUE TITLE
Network configuration 

### ISSUE THREAD

**Issue by AlexeyBarsuk** [MicroPhase/antsdr-fw-patch#9]
I'm using antsdr e310 in SD card mode. I connect it to host over Ethernet cable. I was not able to configure ip address of device like it is described here https://wiki.analog.com/university/tools/pluto/users/customizing. I also tried to set USB_ETHERNET parameters, and after that I was able to ping (see) device in Ethernet network. It looks strange, that settings in [NETWORK] section affect usb adapter, and settings under [USB_ETHERNET] affects Ethernet adapter

![Снимок экрана 2023-07-28 в 19 36 38](https://github.com/MicroPhase/antsdr-fw-patch/assets/26286722/80c46c6d-cad9-4c5b-842b-ef997067c7b1)

**Comment by lone-boy** [comment]
@ AlexeyBarsuk 
Yes, I'm very sorry, I reversed this when making the image. ipaddr corresponds to the USB ip, and ipaddr_eth is the network port ip.

**Comment by lone-boy** [comment]
This issue is fixed in v0.38.
